AirOxa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('users.urls', namespace='users')),
    path('profile/', include('profiles.urls', namespace='profiles')),
]

urlpatterns += [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
]

profiles/urls.py
from django.urls import path, re_path

from .views import (
	signup, ProfileUpdateView, account_activation_sent_view, account_activate
)

app_name = 'profiles'

urlpatterns = [
	path('', signup, name='profile-signup'),
	path('<int:pk>/edit/', ProfileUpdateView.as_view(), name='profile-edit'),
]

urlpatterns += [
	path('account-activation-sent/', account_activation_sent_view, name='account-activation-sent'),
	path('activate/<uidb64>/<token>/',
		account_activate, name='activate'),
]

users/urls.py
from django.urls import path

from .views import home_view, signup_view, dashboard_view

app_name = "users"

urlpatterns = [
    path('', home_view, name='home'),
    path('signup/', signup_view, name='sign-up'),
    path('dashboard/', dashboard_view, name='dashboard'),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	bio = models.CharField(max_length=50, blank=True)
	location = models.CharField(max_length=30)
	email_confirmed = models.BooleanField(default=False)


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)
	instance.profile.save()

users/models.py
from django.db import models

# Create your models here.

profiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
	username = forms.CharField(
		label='',
		max_length=30,
		min_length=5,
		required=True,
		widget=forms.TextInput(
			attrs={
				"placeholder": "Username",
				"class": "form-control"
			}
		)
	)

	email = forms.EmailField(
		label='',
		max_length=255,
		required=True,
		widget=forms.EmailInput(
			attrs={
				"placeholder": "Email",
				"class": "form-control"
			}
		)
	)

	password1 = forms.CharField(
		label='',
		max_length=30,
		min_length=8,
		required=True,
		widget=forms.PasswordInput(
			attrs={
				"placeholder": "Password",
				"class": "form-control"
			}
		)
	)

	password2 = forms.CharField(
		label='',
		max_length=30,
		min_length=8,
		required=True,
		widget=forms.PasswordInput(
			attrs={
				"placeholder": "Confirm Password",
				"class": "form-control"
			}
		)
	)

	location = forms.CharField(
		label='',
		max_length=30,
		required=False,
		widget=forms.HiddenInput(
			attrs={
				"display": "none"
			}
		)
	)

	class Meta:
		model = User
		fields = ('username', 'email', 'password1', 'password2', 'location')

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
	email = forms.EmailField(
		label='',
		max_length=254,
		widget=forms.EmailInput(
			attrs={
				"placeholder": "Email",
				"class": "form-control"
			}
		)
	)

	username = forms.CharField(
		label='',
		max_length=30,
		min_length=5,
		required=True,
		widget=forms.TextInput(
			attrs={
				"placeholder": "Username",
				"class": "form-control"
			}
		)
	)

	password1 = forms.CharField(
		label='',
		max_length=30,
		min_length=8,
		required=True,
		widget=forms.PasswordInput(
			attrs={
				"placeholder": "Password",
				"class": "form-control"
			}
		)
	)

	password2 = forms.CharField(
		label='',
		max_length=30,
		min_length=8,
		required=True,
		widget=forms.PasswordInput(
			attrs={
				"placeholder": "Confirm Password",
				"class": "form-control"
			}
		)
	)
	
	class Meta:
		model = User
		fields = ('username', 'email', 'password1', 'password2')

profiles/views.py
from django.shortcuts import render
from django.contrib.auth import login, authenticate
from django.views.generic import UpdateView
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.contrib.auth import get_user_model

from .forms import SignUpForm
from .models import Profile
from .utils import get_location_from_ip
from .tokens import account_activation_token

User = get_user_model()

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            user.profile.location = form.cleaned_data.get('location')
            ip_address = user.profile.location
            location = get_location_from_ip(ip_address)
            print(location)
            user.profile.location = location
            user.save()
            current_site = get_current_site(request)
            subject = "Activate your Django Serives Account"
            message = render_to_string('registration/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user)
            })
            user.email_user(subject, message)
            return redirect('profiles:account-activation-sent')
    else:
        form = SignUpForm()
    return render(request, 'app/signup.html', {
        'form': form,
        'profile': True
    })


def account_activation_sent_view(request):
    return render(request, 'registration/account_activation_sent.html')


def account_activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        print(uid)
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist) as e:
        print(e)
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        login(request, user)
        return redirect('users:dashboard')
    else:
        return render(request, 'registration/account_activation_invalid.html')


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile
    template_name = "app/profile_edit.html"
    fields = ('bio',)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .forms import SignUpForm

def signup_view(request):
	if request.user.is_authenticated:
		return redirect('users:dashboard')
	if request.method == "POST":
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password1')
			user = authenticate(username=username, password=password)
			login(request, user)
			return redirect('users:dashboard')
		else:
			messages.error(request, 'Correct the errors below')
	else:
		form = SignUpForm()

	return render(request, 'app/signup.html', {'form': form})


@login_required
def dashboard_view(request):
	return render(request, 'app/dashboard.html')


def home_view(request):
	return render(request, 'app/home.html')

templates/app/dashboard.html
{% extends "base.html" %}
<!-- {% load socialaccount %} -->
{% block title %}
	Dashboard
{% endblock %}

{% block content %}

	{% if messages %}

	    {% for message in messages %}

		<!--Panel-->
		<div class="card border-success mb-3">
		    <div class="card-header text-danger">
		        <p class="card-title">{{ message }}</p>
		    </div>
		</div>
		<!--/.Panel-->
	    
	    {% endfor %}

	{% endif %}
	<div style="color: aliceblue;">
	<h1 class="mt-5 text-center">Welcome {{ request.user.name }}</h1>
	<p class="text-left mt-5">Name: {{ user }}</p>
	<p class="text-left">Joined: {{ user.profile.timestamp }}</p>
	<p class="text-left">Email: {{ user.email }}</p>
</div>
{% endblock content %}

templates/app/home.html
{% extends "base.html" %}

{% block title %}
	Home
{% endblock %}

{% block content %}

	{{ block.super }}

{% endblock content %}

templates/app/profile_edit.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}
	Edit Name
{% endblock %}

{% block content %}
	
	<div class="text-left mt-5 container">
		{% for field in form %}
		    <p>
	        	{{ field.label_tag }}
	        	{{ field|attr:"rows:20"|attr:"cols:20" }}
		        <!-- {% if field.help_text %}
		          <small style="color: grey">{{ field.help_text }}</small>
		        {% endif %} -->
		        {% for error in field.errors %}
		          <p style="color: red">{{ error }}</p>
		        {% endfor %}
		    </p>
		{% endfor %}
	</div>

{% endblock %}

templates/app/signup.html
{% extends "base.html" %}
{% load socialaccount %}
{% block title %}
	Sign Up
{% endblock %}

{% block content %}
	
	{% if messages %}

	    {% for message in messages %}

		<!--Panel-->
		<div class="card border-danger mb-3">
		    <div class="card-header text-danger">
		        <p class="card-title">{{ message }}</p>
		    </div>
		</div>
		<!--/.Panel-->
	    
	    {% endfor %}

	{% endif %}

<div class="container mt-4">
<div class="row">
	<div class="col-md-4">
		
		<div class="list-group mt-5">
		    <a href="{% url 'users:home' %}" class="list-group-item list-group-item-action waves-effect">Home</a>
			{% if profile %}
		    <a href="{% url 'profiles:profile-signup' %}" class="list-group-item bg-secondary text-white waves-effect">
		    		Profile Sign up
		    	{% else %}
		    	<a href="{% url 'users:sign-up' %}" class="list-group-item bg-secondary text-white waves-effect">
		    		Sign up
		    {% endif %}		    	
		    </a>
		    <a href="{% url 'login' %}" class="list-group-item list-group-item-action waves-effect">Login</a>
		    <a href="{% url 'users:dashboard' %}" class="list-group-item list-group-item-action waves-effect">Dashboard</a>
		    <a href="{% url 'users:dashboard' %}" class="list-group-item list-group-item-action waves-effect">Profile</a>
		</div>

	</div>

		<div class="col-md-2"></div>

	<div class="col-md-4">
		<!-- Default form register -->
		<form class="border mt-5 border-secondary text-center p-3" method="post">
			{% csrf_token %}
		    <p class="h4 mb-4 text-secondary text-center">Sign up</p>

		    <!-- {{ form.as_p }} -->

			{% for field in form %}
		    <p>
	        	{{ field.label_tag }}
	        	{{ field }}
		        <!-- {% if field.help_text %}
		          <small style="color: grey">{{ field.help_text }}</small>
		        {% endif %} -->
		        {% for error in field.errors %}
		          <p style="color: red">{{ error }}</p>
		        {% endfor %}
		    </p>
		    {% endfor %}

		    <!-- Sign up button -->
		    <button class="btn btn-secondary my-4 btn-block" type="submit">Sign up</button>

		    <!-- Social register -->
		    <p style="color: yellow;">or sign up with:</p>

		    <a type="button" class="light-blue-text mx-2">
		        <i class="fa fa-facebook"></i>
		    </a>
		    <a type="button" class="light-blue-text mx-2" href="{% provider_login_url 'google' %}">
		        <i class="fa fa-google"></i>
		    </a>
		    <a type="button" class="light-blue-text mx-2">
		        <i class="fa fa-linkedin"></i>
		    </a>
		    <a type="button" class="light-blue-text mx-2">
		        <i class="fa fa-github"></i>
		    </a>

		    <hr>

		    <!-- Terms of service -->
		    <p style="color: white;">By clicking
		        <em>Sign up</em> you agree to our
		        <a href="" target="_blank">terms of service</a>
		    </p>
		</form>
		<!-- Default form register -->
	</div>

	<div class="col-md-2"></div>

</div>
</div>

{% block script %}
<script type="text/javascript">
	function get_ip(json) {
		$("#id_location").val(json.ip);
	}
</script>

<script src="https://api.ipify.org?format=jsonp&callback=get_ip"></script>
{% endblock %}

{% endblock %}

templates/base.html
{% load static %}
{% load socialaccount %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Django App | {% block title %}{% endblock %}</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
  </head>

  <body style="background: rgb(2, 37, 65);">

    {% if not form %}
      {% include "navbar.html" %}
    {% endif %}

      <!-- Start your project here-->
      <div style="height: 100vh" class="container">

      	{% block content %}

          <div class="flex-center flex-column" style="color:aliceblue">
              <h1 class="animated fadeIn mb-4">Welcome to AirOxa Innovative</h1>

              <h5 class="animated fadeIn mb-3">Thank you for using our product. We're glad you're with us.</h5>

              <p class="animated fadeIn text-muted" style="color:greenyellow">AirOxa Team</p>
          </div>

        {% endblock %}
      </div>
      <!-- /Start your project here-->

    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    {% block script %}
    {% endblock %}
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
</body>

</html>

templates/navbar.html
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark secondary-color mb-5">

<div class="container">
    <!-- Navbar brand -->
    <a style="margin-right: 20px;"><img src="/static/img/airoxa.jpeg" width="40" height="50"></a>

    <!-- <a class="navbar-brand" href="{% url 'users:home' %}" style="font-weight:bold;">AirOxa</a> -->

    <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'users:home' %}">Home
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:dashboard' %}">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:sign-up' %}">Sign up</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profiles:profile-signup' %}">Profile SignUp</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profiles:profile-edit' user.profile.id %}">Profile</a>
            </li>
            {% endif %}

        </ul>
        <!-- Links -->

        <!-- login and logout buttons -->
        <div class="my-1 mr-3">
            {% if user.is_authenticated %}
                <a class="btn btn-outline-white btn-md my-2 my-sm-0 ml-3" href="{% url 'logout' %}">Logout</a>
        </div>
        <div class="my-1 mr-3">
                <!-- user icon -->
                <div class="white-text">
                   <i class="fa fa-user" aria-hidden="true"></i>
                   {{ request.user }}
                </div>
            {% else %}
                <a class="btn btn-outline-white btn-md my-2 my-sm-0 ml-3" href="{% url 'login' %}">Login</a>
            {% endif %}
        </div>        
    </div>
    <!-- Collapsible content -->

</div>

</nav>
<!--/.Navbar-->